spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leafgrow_project
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
  mail:
    username: leafgrow@gmail.com
    password: yhwnykriinuapexe
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

key:
  access: vCzzRbdnRQnZaz0yMft6CM6XOFxH5RFXlEp2SfJaENg=
  refresh: w4nW81yrLjMg5OEIoiZEiGSHCOgZJwqadOF2Y3LhSUQ=

logging:
  file:
    name: logs/log.log
  level:
    root: info
